C======================================================================
C     ogden_umat.for
C
C     Generated by abaqus_ufl v0.1.0
C     Material: OgdenOneTerm
C     Matrix backend: iterative
C     Algorithmic tangent: major-symmetric
C     Props: mu=1.0, alpha=3.5, K=100.0
C     NPROPS = 3
C
C     This file is self-contained. Drop it into your Abaqus job:
C       abaqus job=my_job user=ogden_umat.for
C======================================================================

C======================================================================
C     Section 1: Abaqus UMAT interface
C======================================================================
C======================================================================
C     UMAT: Standard Abaqus user material interface
C
C     Generated by abaqus_ufl for material: ogdenoneterm
C     NPROPS = 3
C======================================================================
      SUBROUTINE UMAT(STRESS, STATEV, DDSDDE, SSE, SPD, SCD,
     &  RPL, DDSDDT, DRPLDE, DRPLDT,
     &  STRAN, DSTRAN, TIME, DTIME, TEMP, DTEMP, PREDEF, DPRED,
     &  CMNAME, NDI, NSHR, NTENS, NSTATV, PROPS, NPROPS,
     &  COORDS, DROT, PNEWDT, CELENT, DFGRD0, DFGRD1,
     &  NOEL, NPT, LAYER, KSPT, JSTEP, KINC)

      IMPLICIT NONE

C     --- Abaqus interface variables ---
      CHARACTER*80 CMNAME
      INTEGER NDI, NSHR, NTENS, NSTATV, NPROPS
      INTEGER NOEL, NPT, LAYER, KSPT, JSTEP(4), KINC

      DOUBLE PRECISION STRESS(NTENS), STATEV(NSTATV)
      DOUBLE PRECISION DDSDDE(NTENS,NTENS)
      DOUBLE PRECISION SSE, SPD, SCD, RPL, DTIME, TEMP, DTEMP
      DOUBLE PRECISION DDSDDT(NTENS), DRPLDE(NTENS), DRPLDT
      DOUBLE PRECISION STRAN(NTENS), DSTRAN(NTENS)
      DOUBLE PRECISION TIME(2), PREDEF(1), DPRED(1)
      DOUBLE PRECISION PROPS(NPROPS), COORDS(3)
      DOUBLE PRECISION DROT(3,3), PNEWDT, CELENT
      DOUBLE PRECISION DFGRD0(3,3), DFGRD1(3,3)

C     --- Local variables ---
      DOUBLE PRECISION :: F(3,3), P_real(3,3)
      DOUBLE PRECISION :: dPdF(3,3,3,3)
      DOUBLE COMPLEX :: Fz(3,3), Pz(3,3)
      INTEGER :: i, j

C     --- Initialize optional Abaqus outputs ---
      RPL = 0.0d0
      DDSDDT = 0.0d0
      DRPLDE = 0.0d0
      DRPLDT = 0.0d0
      DDSDDE = 0.0d0

      IF (NDI .NE. 3 .OR. NSHR .NE. 3 .OR. NTENS .NE. 6) THEN
        PNEWDT = 0.5d0
        RETURN
      END IF

C     --- Get deformation gradient ---
      DO i = 1, 3
        DO j = 1, 3
          F(i,j) = DFGRD1(i,j)
        END DO
      END DO

C     --- Compute PK1 stress (real evaluation) ---
      CALL real2complex33(F, Fz)
      CALL ogdenoneterm_stress_PK1(Fz, PROPS, Pz)
      DO i = 1, 3
        DO j = 1, 3
          P_real(i,j) = DBLE(Pz(i,j))
        END DO
      END DO

C     --- Compute dP/dF via complex step ---
      CALL ogdenoneterm_cs_dPdF(F, PROPS, dPdF)

C     --- Convert PK1 -> Cauchy + Jaumann tangent (Voigt) ---
      CALL pk1_to_cauchy_jaumann(F, P_real, dPdF, STRESS, DDSDDE)

      RETURN
      END SUBROUTINE UMAT

C======================================================================
C     Section 2: Material stress: ogdenoneterm_stress_PK1
C======================================================================
      SUBROUTINE ogdenoneterm_stress_PK1(F, props, P_out)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: F(3,3)
      DOUBLE PRECISION, INTENT(IN) :: props(3)
      DOUBLE COMPLEX, INTENT(OUT) :: P_out(3,3)

      DOUBLE COMPLEX :: det33z
      DOUBLE COMPLEX :: cs_sin
      DOUBLE COMPLEX :: cs_cos
      DOUBLE COMPLEX :: cs_tan
      DOUBLE COMPLEX :: cs_sinh
      DOUBLE COMPLEX :: cs_cosh
      DOUBLE COMPLEX :: cs_tanh
      DOUBLE COMPLEX :: cs_atan
      DOUBLE COMPLEX :: cs_acos
      DOUBLE COMPLEX :: cs_erf
      DOUBLE COMPLEX :: cs_erfc
      DOUBLE COMPLEX :: AT1(3,3)
      DOUBLE COMPLEX :: MM2(3,3)
      DOUBLE COMPLEX :: C(3,3)
      DOUBLE COMPLEX :: lam(3)
      DOUBLE COMPLEX :: V(3,3)
      DOUBLE COMPLEX :: ARR3(3,3)
      DOUBLE COMPLEX :: D(3,3)
      DOUBLE COMPLEX :: MM4(3,3)
      DOUBLE COMPLEX :: INV5(3,3)
      DOUBLE COMPLEX :: MM6(3,3)
      DOUBLE COMPLEX :: S(3,3)
      DOUBLE COMPLEX :: MM7(3,3)
      DOUBLE COMPLEX :: J
      DOUBLE COMPLEX :: scale
      DOUBLE COMPLEX :: lb1
      DOUBLE COMPLEX :: lb2
      DOUBLE COMPLEX :: lb3
      DOUBLE COMPLEX :: w1
      DOUBLE COMPLEX :: w2
      DOUBLE COMPLEX :: w3
      DOUBLE COMPLEX :: mean_w
      DOUBLE COMPLEX :: coef
      DOUBLE COMPLEX :: vol
      DOUBLE COMPLEX :: t1
      DOUBLE COMPLEX :: t2
      DOUBLE COMPLEX :: t3
      INTEGER :: ii, jj

      J = det33z(F)
      CALL transpose33z(F, AT1)
      CALL matmul33z(AT1, F, MM2)
      C = MM2
      CALL eig33z(C, lam, V)
      scale = (J ** ((-DCMPLX(1.000000000000000d+00, 0.0d0)) /
     &DCMPLX(3.000000000000000d+00, 0.0d0)))
      lb1 = (scale * SQRT(lam(1)))
      lb2 = (scale * SQRT(lam(2)))
      lb3 = (scale * SQRT(lam(3)))
      w1 = (lb1 ** DCMPLX(props(2), 0.0d0))
      w2 = (lb2 ** DCMPLX(props(2), 0.0d0))
      w3 = (lb3 ** DCMPLX(props(2), 0.0d0))
      mean_w = (((w1 + w2) + w3) / DCMPLX(3.000000000000000d+00, 0.0d0))
      coef = ((DCMPLX(2.000000000000000d+00, 0.0d0) * DCMPLX(props(1),
     &0.0d0)) / DCMPLX(props(2), 0.0d0))
      vol = (DCMPLX(props(3), 0.0d0) * LOG(J))
      t1 = ((coef * (w1 - mean_w)) + vol)
      t2 = ((coef * (w2 - mean_w)) + vol)
      t3 = ((coef * (w3 - mean_w)) + vol)
      ARR3(1,1) = (t1 / lam(1))
      ARR3(1,2) = DCMPLX(0.000000000000000d+00, 0.0d0)
      ARR3(1,3) = DCMPLX(0.000000000000000d+00, 0.0d0)
      ARR3(2,1) = DCMPLX(0.000000000000000d+00, 0.0d0)
      ARR3(2,2) = (t2 / lam(2))
      ARR3(2,3) = DCMPLX(0.000000000000000d+00, 0.0d0)
      ARR3(3,1) = DCMPLX(0.000000000000000d+00, 0.0d0)
      ARR3(3,2) = DCMPLX(0.000000000000000d+00, 0.0d0)
      ARR3(3,3) = (t3 / lam(3))
      D = ARR3
      CALL matmul33z(V, D, MM4)
      CALL inv33z(V, INV5)
      CALL matmul33z(MM4, INV5, MM6)
      S = MM6
      CALL matmul33z(F, S, MM7)

      DO ii = 1, 3
        DO jj = 1, 3
          P_out(ii,jj) = MM7(ii,jj)
        END DO
      END DO

      RETURN
      END SUBROUTINE ogdenoneterm_stress_PK1

C======================================================================
C     Section 3: Complex-step tangent: d(PK1)/d(F)
C======================================================================
      SUBROUTINE ogdenoneterm_cs_dPdF(F, props, dPdF)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: F(3,3)
      DOUBLE PRECISION, INTENT(IN)  :: props(3)
      DOUBLE PRECISION, INTENT(OUT) :: dPdF(3,3,3,3)

      DOUBLE PRECISION, PARAMETER :: CS_H = 1.0d-10
      DOUBLE COMPLEX :: Fz(3,3), Pz(3,3)
      INTEGER :: k, l, i, j

      DO k = 1, 3
        DO l = 1, 3
          CALL real2complex33(F, Fz)
          Fz(k,l) = Fz(k,l) + DCMPLX(0.0d0, CS_H)
          CALL ogdenoneterm_stress_PK1(Fz, props, Pz)
          DO i = 1, 3
            DO j = 1, 3
              dPdF(i,j,k,l) = AIMAG(Pz(i,j)) / CS_H
            END DO
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE ogdenoneterm_cs_dPdF

C======================================================================
C     Section 4: PK1 -> Cauchy stress + Jaumann tangent (Voigt)
C======================================================================

C----------------------------------------------------------------------
C     pk1_to_cauchy_jaumann: Convert PK1 stress and tangent to
C     Cauchy stress (Voigt) and Jaumann DDSDDE (Voigt 6x6)
C
C     For Abaqus/Standard solid continuum UMATs, DDSDDE is the spatial
C     tangent in tau^J_ij = J * DDSDDE_ijkl * D_kl, where tau = J*sigma
C     and ^J denotes the Jaumann rate of Kirchhoff stress.
C
C     DDSDDE_ijkl = (1/J)*AFF_ijkl
C                  - delta_ik*sigma_jl                 (bookkeeping)
C                  + 0.5*(sigma_ik*delta_jl + sigma_jk*delta_il
C                       + sigma_il*delta_jk + sigma_jl*delta_ik)
C
C     where AFF_ijkl = sum_{J,L} dPdF(i,J,k,L) * F(j,J) * F(l,L).
C
C     The bookkeeping line is non-optional. The chain rule on
C     P_iJ = F_iI * S_IJ gives AFF/J = c_Truesdell + delta_ik*sigma_jl;
C     subtracting that delta-sigma piece recovers c_Truesdell, to which
C     the symmetric (sigma cdya I + I cdya sigma) block is then added.
C
C     Abaqus Voigt order: 11, 22, 33, 12, 13, 23
C----------------------------------------------------------------------
      SUBROUTINE pk1_to_cauchy_jaumann(F, P, dPdF, STRESS, DDSDDE)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: F(3,3), P(3,3), dPdF(3,3,3,3)
      DOUBLE PRECISION, INTENT(OUT) :: STRESS(6), DDSDDE(6,6)

            DOUBLE PRECISION :: Jdet, det33d, JdetInv
      DOUBLE PRECISION :: sigma(3,3)
      DOUBLE PRECISION :: c(3,3,3,3)
      DOUBLE PRECISION :: AFF
      DOUBLE PRECISION :: delta(3,3)
      INTEGER :: i, j, k, l, J1, L1

C     Voigt index map: (1,1)->1, (2,2)->2, (3,3)->3,
C                      (1,2)->4, (1,3)->5, (2,3)->6
      INTEGER :: voigt_i(6), voigt_j(6)
      DATA voigt_i /1, 2, 3, 1, 1, 2/
      DATA voigt_j /1, 2, 3, 2, 3, 3/

C     Determinant
      Jdet = det33d(F)
      JdetInv = 1.0d0 / Jdet

C     Cauchy stress: sigma = (1/J) P F^T
      DO i = 1, 3
        DO j = 1, 3
          sigma(i,j) = 0.0d0
          DO J1 = 1, 3
            sigma(i,j) = sigma(i,j) + P(i,J1) * F(j,J1)
          END DO
                    sigma(i,j) = sigma(i,j) * JdetInv
        END DO
      END DO

C     DDSDDE: (1/J)*AFF
C                  - delta_ik*sigma_jl
C                  + 0.5*(sigma_ik*delta_jl + sigma_jk*delta_il
C                       + sigma_il*delta_jk + sigma_jl*delta_ik)
C     where AFF_ijkl = sum_{J,L} dPdF(i,J,k,L) * F(j,J) * F(l,L)
C---------------------------------------------------------------------
      DO i = 1, 3
        DO j = 1, 3
          IF (i .EQ. j) THEN
            delta(i,j) = 1.0d0
          ELSE
            delta(i,j) = 0.0d0
          END IF
        END DO
      END DO

      DO i = 1, 3
        DO j = 1, 3
          DO k = 1, 3
            DO l = 1, 3
C             AFF_ijkl = sum_{J,L} dPdF(i,J,k,L) * F(j,J) * F(l,L)
              AFF = 0.0d0
              DO J1 = 1, 3
                DO L1 = 1, 3
                  AFF = AFF + dPdF(i,J1,k,L1)*F(j,J1)*F(l,L1)
                END DO
              END DO
                            c(i,j,k,l) = AFF * JdetInv
     &          - delta(i,k)*sigma(j,l)
     &          + 0.5d0*(sigma(i,k)*delta(j,l) + sigma(j,k)*delta(i,l)
     &                 + sigma(i,l)*delta(j,k) + sigma(j,l)*delta(i,k))
            END DO
          END DO
        END DO
      END DO

C     Pack symmetric stress/strain component pairs into Voigt 6x6.
C     Preserve all 36 computed entries. Major symmetry is a material
C     validation/deck contract, not guaranteed by this kinematic conversion.
      DO i = 1, 6
        STRESS(i) = sigma(voigt_i(i), voigt_j(i))
      END DO

      DO i = 1, 6
        DO j = 1, 6
          DDSDDE(i,j) = c(voigt_i(i), voigt_j(i),
     &                      voigt_i(j), voigt_j(j))
        END DO
      END DO

      RETURN
      END SUBROUTINE pk1_to_cauchy_jaumann


C======================================================================
C     Section 5: Tensor operations (det33, inv33, matmul33, etc.)
C======================================================================
C======================================================================
C     tensor_ops.for -- Complex-arithmetic tensor utilities
C
C     Provides det33, inv33, matmul33, transpose33, outer33 for
C     DOUBLE COMPLEX arguments. Also provides real-only wrappers.
C
C     Design:  1:1 mirror of the package's Python tensor helpers
C     Purpose: Foundation for complex-step tangent engine
C
C     Convention: All 3x3 matrices stored as (3,3) arrays
C                 Index order: (row, col) = (i, J)
C======================================================================

C----------------------------------------------------------------------
C     det33z: Determinant of 3x3 complex matrix
C----------------------------------------------------------------------
      FUNCTION det33z(A) RESULT(d)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: A(3,3)
      DOUBLE COMPLEX :: d

      d = A(1,1)*(A(2,2)*A(3,3) - A(2,3)*A(3,2))
     &  - A(1,2)*(A(2,1)*A(3,3) - A(2,3)*A(3,1))
     &  + A(1,3)*(A(2,1)*A(3,2) - A(2,2)*A(3,1))

      RETURN
      END FUNCTION det33z

C----------------------------------------------------------------------
C     det33d: Determinant of 3x3 real matrix
C----------------------------------------------------------------------
      FUNCTION det33d(A) RESULT(d)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN) :: A(3,3)
      DOUBLE PRECISION :: d

      d = A(1,1)*(A(2,2)*A(3,3) - A(2,3)*A(3,2))
     &  - A(1,2)*(A(2,1)*A(3,3) - A(2,3)*A(3,1))
     &  + A(1,3)*(A(2,1)*A(3,2) - A(2,2)*A(3,1))

      RETURN
      END FUNCTION det33d

C----------------------------------------------------------------------
C     inv33z: Inverse of 3x3 complex matrix
C----------------------------------------------------------------------
      SUBROUTINE inv33z(A, Ainv)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: Ainv(3,3)
      DOUBLE COMPLEX :: d, det33z

      d = det33z(A)

      Ainv(1,1) = (A(2,2)*A(3,3) - A(2,3)*A(3,2)) / d
      Ainv(1,2) = (A(1,3)*A(3,2) - A(1,2)*A(3,3)) / d
      Ainv(1,3) = (A(1,2)*A(2,3) - A(1,3)*A(2,2)) / d
      Ainv(2,1) = (A(2,3)*A(3,1) - A(2,1)*A(3,3)) / d
      Ainv(2,2) = (A(1,1)*A(3,3) - A(1,3)*A(3,1)) / d
      Ainv(2,3) = (A(1,3)*A(2,1) - A(1,1)*A(2,3)) / d
      Ainv(3,1) = (A(2,1)*A(3,2) - A(2,2)*A(3,1)) / d
      Ainv(3,2) = (A(1,2)*A(3,1) - A(1,1)*A(3,2)) / d
      Ainv(3,3) = (A(1,1)*A(2,2) - A(1,2)*A(2,1)) / d

      RETURN
      END SUBROUTINE inv33z

C----------------------------------------------------------------------
C     inv33d: Inverse of 3x3 real matrix
C----------------------------------------------------------------------
      SUBROUTINE inv33d(A, Ainv)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: Ainv(3,3)
      DOUBLE PRECISION :: d, det33d

      d = det33d(A)

      Ainv(1,1) = (A(2,2)*A(3,3) - A(2,3)*A(3,2)) / d
      Ainv(1,2) = (A(1,3)*A(3,2) - A(1,2)*A(3,3)) / d
      Ainv(1,3) = (A(1,2)*A(2,3) - A(1,3)*A(2,2)) / d
      Ainv(2,1) = (A(2,3)*A(3,1) - A(2,1)*A(3,3)) / d
      Ainv(2,2) = (A(1,1)*A(3,3) - A(1,3)*A(3,1)) / d
      Ainv(2,3) = (A(1,3)*A(2,1) - A(1,1)*A(2,3)) / d
      Ainv(3,1) = (A(2,1)*A(3,2) - A(2,2)*A(3,1)) / d
      Ainv(3,2) = (A(1,2)*A(3,1) - A(1,1)*A(3,2)) / d
      Ainv(3,3) = (A(1,1)*A(2,2) - A(1,2)*A(2,1)) / d

      RETURN
      END SUBROUTINE inv33d

C----------------------------------------------------------------------
C     matmul33z: C = A * B for 3x3 complex matrices
C     (Explicit loop -- avoids MATMUL intrinsic for portability)
C----------------------------------------------------------------------
      SUBROUTINE matmul33z(A, B, C)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3), B(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: C(3,3)
      INTEGER :: i, j, k

      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = (0.0d0, 0.0d0)
          DO k = 1, 3
            C(i,j) = C(i,j) + A(i,k) * B(k,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE matmul33z

C----------------------------------------------------------------------
C     matmul33d: C = A * B for 3x3 real matrices
C----------------------------------------------------------------------
      SUBROUTINE matmul33d(A, B, C)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3), B(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: C(3,3)
      INTEGER :: i, j, k

      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = 0.0d0
          DO k = 1, 3
            C(i,j) = C(i,j) + A(i,k) * B(k,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE matmul33d

C----------------------------------------------------------------------
C     transpose33z: B = A^T for 3x3 complex matrix
C----------------------------------------------------------------------
      SUBROUTINE transpose33z(A, AT)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: AT(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          AT(i,j) = A(j,i)
        END DO
      END DO

      RETURN
      END SUBROUTINE transpose33z

C----------------------------------------------------------------------
C     transpose33d: B = A^T for 3x3 real matrix
C----------------------------------------------------------------------
      SUBROUTINE transpose33d(A, AT)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: AT(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          AT(i,j) = A(j,i)
        END DO
      END DO

      RETURN
      END SUBROUTINE transpose33d

C----------------------------------------------------------------------
C     matvec33z: y = A * x for 3x3 complex matrix and 3-vector
C----------------------------------------------------------------------
      SUBROUTINE matvec33z(A, x, y)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3), x(3)
      DOUBLE COMPLEX, INTENT(OUT) :: y(3)
      INTEGER :: i, k

      DO i = 1, 3
        y(i) = (0.0d0, 0.0d0)
        DO k = 1, 3
          y(i) = y(i) + A(i,k) * x(k)
        END DO
      END DO

      RETURN
      END SUBROUTINE matvec33z

C----------------------------------------------------------------------
C     matvec33d: y = A * x for 3x3 real matrix and 3-vector
C----------------------------------------------------------------------
      SUBROUTINE matvec33d(A, x, y)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3), x(3)
      DOUBLE PRECISION, INTENT(OUT) :: y(3)
      INTEGER :: i, k

      DO i = 1, 3
        y(i) = 0.0d0
        DO k = 1, 3
          y(i) = y(i) + A(i,k) * x(k)
        END DO
      END DO

      RETURN
      END SUBROUTINE matvec33d

C----------------------------------------------------------------------
C     eye33z: A = I (3x3 complex identity)
C----------------------------------------------------------------------
      SUBROUTINE eye33z(A)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(OUT) :: A(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          IF (i .EQ. j) THEN
            A(i,j) = (1.0d0, 0.0d0)
          ELSE
            A(i,j) = (0.0d0, 0.0d0)
          END IF
        END DO
      END DO

      RETURN
      END SUBROUTINE eye33z

C----------------------------------------------------------------------
C     eye33d: A = I (3x3 real identity)
C----------------------------------------------------------------------
      SUBROUTINE eye33d(A)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: A(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          IF (i .EQ. j) THEN
            A(i,j) = 1.0d0
          ELSE
            A(i,j) = 0.0d0
          END IF
        END DO
      END DO

      RETURN
      END SUBROUTINE eye33d

C----------------------------------------------------------------------
C     real2complex33: Convert real 3x3 to complex 3x3
C----------------------------------------------------------------------
      SUBROUTINE real2complex33(A_real, A_cmplx)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A_real(3,3)
      DOUBLE COMPLEX,   INTENT(OUT) :: A_cmplx(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          A_cmplx(i,j) = DCMPLX(A_real(i,j), 0.0d0)
        END DO
      END DO

      RETURN
      END SUBROUTINE real2complex33

C----------------------------------------------------------------------
C     real2complex3: Convert real 3-vector to complex 3-vector
C----------------------------------------------------------------------
      SUBROUTINE real2complex3(v_real, v_cmplx)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: v_real(3)
      DOUBLE COMPLEX,   INTENT(OUT) :: v_cmplx(3)
      INTEGER :: i

      DO i = 1, 3
        v_cmplx(i) = DCMPLX(v_real(i), 0.0d0)
      END DO

      RETURN
      END SUBROUTINE real2complex3

C======================================================================
C     Matrix functions for tensor_ops.for
C     Eigendecomposition-based (Approach A) + iterative fallbacks (B)
C
C     All DOUBLE COMPLEX, CS-safe. See MATRIX_FUNCTIONS_DESIGN.md.
C
C     Subroutines:
C       cross3z        -- cross product of complex 3-vectors
C       outer33z       -- outer product of two complex 3-vectors
C       sym3z          -- symmetric 3x3 tensor from 6 unique entries
C       eig33z         -- eigenvalues/vectors of 3x3 symmetric matrix
C       sqrtm33z       -- matrix square root via eigendecomposition
C       logm33z        -- matrix logarithm via eigendecomposition
C       expm33z        -- matrix exponential via eigendecomposition
C       polar33z       -- right polar decomposition F = R * U
C       sqrtm33z_iter  -- matrix square root (Denman-Beavers)
C       logm33z_iter   -- matrix logarithm (inv scaling & squaring)
C       expm33z_iter   -- matrix exponential (scaling & squaring + Pade)
C======================================================================

C----------------------------------------------------------------------
C     cross3z: Cross product of two complex 3-vectors
C----------------------------------------------------------------------
      SUBROUTINE cross3z(a, b, c)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a(3), b(3)
      DOUBLE COMPLEX, INTENT(OUT) :: c(3)

      c(1) = a(2)*b(3) - a(3)*b(2)
      c(2) = a(3)*b(1) - a(1)*b(3)
      c(3) = a(1)*b(2) - a(2)*b(1)

      RETURN
      END SUBROUTINE cross3z

C----------------------------------------------------------------------
C     outer33z: Outer product of two complex 3-vectors, C_ij = a_i b_j
C----------------------------------------------------------------------
      SUBROUTINE outer33z(a, b, C)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a(3), b(3)
      DOUBLE COMPLEX, INTENT(OUT) :: C(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = a(i) * b(j)
        END DO
      END DO

      RETURN
      END SUBROUTINE outer33z

C----------------------------------------------------------------------
C     sym3z: Symmetric 3x3 tensor from its 6 unique entries
C            T = [[a11, a12, a13],
C                 [a12, a22, a23],
C                 [a13, a23, a33]]
C----------------------------------------------------------------------
      SUBROUTINE sym3z(a11, a22, a33, a12, a13, a23, T)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a11, a22, a33, a12, a13, a23
      DOUBLE COMPLEX, INTENT(OUT) :: T(3,3)

      T(1,1) = a11
      T(2,2) = a22
      T(3,3) = a33
      T(1,2) = a12
      T(2,1) = a12
      T(1,3) = a13
      T(3,1) = a13
      T(2,3) = a23
      T(3,2) = a23

      RETURN
      END SUBROUTINE sym3z

C----------------------------------------------------------------------
C     jacobi33d_vectors: Eigenvectors of a real symmetric 3x3 matrix.
C
C     Fixed cyclic Jacobi sweeps are used only inside the near-diagonal
C     complex-step fallback below.  The input is the selected real or
C     imaginary part of a quasi-degenerate block; Q is real orthogonal.
C----------------------------------------------------------------------
      SUBROUTINE jacobi33d_vectors(M_in, Q)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: M_in(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: Q(3,3)
      DOUBLE PRECISION :: M(3,3), R(3,3), T(3,3)
      DOUBLE PRECISION :: apq, theta, cc, ss
      INTEGER :: pp(3), qq(3)
      INTEGER :: i, pair, pidx, qidx, sweep
      DATA pp /1, 1, 2/
      DATA qq /2, 3, 3/

      M = M_in
      Q = 0.0d0
      DO i = 1, 3
        Q(i,i) = 1.0d0
      END DO

      DO sweep = 1, 12
        DO pair = 1, 3
          pidx = pp(pair)
          qidx = qq(pair)
          apq = M(pidx,qidx)
          IF (ABS(apq) .GT. 0.0d0) THEN
            theta = 0.5d0 * ATAN2(2.0d0*apq,
     &                              M(pidx,pidx)-M(qidx,qidx))
            cc = COS(theta)
            ss = SIN(theta)
            R = 0.0d0
            DO i = 1, 3
              R(i,i) = 1.0d0
            END DO
            R(pidx,pidx) = cc
            R(qidx,qidx) = cc
            R(pidx,qidx) = -ss
            R(qidx,pidx) = ss
            T = MATMUL(TRANSPOSE(R), MATMUL(M, R))
            M = T
            Q = MATMUL(Q, R)
          END IF
        END DO
      END DO

      RETURN
      END SUBROUTINE jacobi33d_vectors

C----------------------------------------------------------------------
C     eig33z_near_diagonal: Quasi-degenerate perturbation fallback.
C
C     This is the generated-Fortran mirror of tensor.py's
C     _eig_near_diagonal. Diagonal entries are grouped by real-part
C     closeness. Within a repeated group, the derivative-carrying
C     imaginary-symmetric deviation selects the CS basis when present;
C     pure value calls use the real deviation. Across distinct groups,
C     first-order eigenvector corrections retain the complex-step
C     off-diagonal perturbation.
C----------------------------------------------------------------------
      SUBROUTINE eig33z_near_diagonal(A, lam, V)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: lam(3), V(3,3)
      DOUBLE COMPLEX :: D(3), group_mean, numerator, gap
      DOUBLE COMPLEX :: zdev, ztmp
      DOUBLE PRECISION :: scale, max_real, max_imag
      DOUBLE PRECISION :: Mreal(3,3), Qreal(3,3)
      DOUBLE PRECISION :: aa, bb, dd, theta, cc, ss
      INTEGER :: order(3), group(3), members(3)
      INTEGER :: i, j, aidx, bidx, col, g, ng, n, pos

      DO i = 1, 3
        D(i) = A(i,i)
        order(i) = i
      END DO

C     Sort diagonal indices by real part.
      DO i = 1, 2
        DO j = i+1, 3
          IF (DBLE(D(order(j))) .LT. DBLE(D(order(i)))) THEN
            pos = order(i)
            order(i) = order(j)
            order(j) = pos
          END IF
        END DO
      END DO

      scale = 1.0d-300
      DO i = 1, 3
        DO j = 1, 3
          scale = MAX(scale, ABS(A(i,j)))
        END DO
      END DO

C     Group adjacent near-equal diagonal values.
      ng = 1
      group(order(1)) = ng
      DO pos = 2, 3
        IF (ABS(DBLE(D(order(pos)))-DBLE(D(order(pos-1))))
     &      .LE. 1.0d-6*scale) THEN
          group(order(pos)) = ng
        ELSE
          ng = ng + 1
          group(order(pos)) = ng
        END IF
      END DO

      V = DCMPLX(0.0d0, 0.0d0)
      lam = DCMPLX(0.0d0, 0.0d0)

      DO g = 1, ng
        n = 0
        DO pos = 1, 3
          i = order(pos)
          IF (group(i) .EQ. g) THEN
            n = n + 1
            members(n) = i
          END IF
        END DO

        IF (n .EQ. 1) THEN
          col = members(1)
          lam(col) = D(col)
          V(col,col) = DCMPLX(1.0d0, 0.0d0)
        ELSE
          group_mean = DCMPLX(0.0d0, 0.0d0)
          DO aidx = 1, n
            i = members(aidx)
            group_mean = group_mean + A(i,i)
          END DO
          group_mean = group_mean / DBLE(n)

          max_real = 0.0d0
          max_imag = 0.0d0
          DO aidx = 1, n
            i = members(aidx)
            DO bidx = 1, n
              j = members(bidx)
              zdev = A(i,j)
              IF (i .EQ. j) zdev = zdev - group_mean
              max_real = MAX(max_real, ABS(DBLE(zdev)))
              max_imag = MAX(max_imag, ABS(AIMAG(zdev)))
            END DO
          END DO

          Mreal = 0.0d0
          DO aidx = 1, n
            i = members(aidx)
            DO bidx = 1, n
              j = members(bidx)
              zdev = A(i,j)
              IF (i .EQ. j) zdev = zdev - group_mean
              IF (max_imag .GT. 0.0d0) THEN
                Mreal(i,j) = AIMAG(zdev)
              ELSE
                Mreal(i,j) = DBLE(zdev)
              END IF
            END DO
          END DO

          Qreal = 0.0d0
          DO i = 1, 3
            Qreal(i,i) = 1.0d0
          END DO
          IF (MAX(max_real, max_imag) .GT. 0.0d0) THEN
            IF (n .EQ. 2) THEN
              i = members(1)
              j = members(2)
              aa = Mreal(i,i)
              bb = Mreal(i,j)
              dd = Mreal(j,j)
              IF (ABS(bb) .GT. 0.0d0) THEN
                theta = 0.5d0 * ATAN2(2.0d0*bb, aa-dd)
                cc = COS(theta)
                ss = SIN(theta)
                Qreal(i,i) = cc
                Qreal(j,i) = ss
                Qreal(i,j) = -ss
                Qreal(j,j) = cc
              END IF
            ELSE
              CALL jacobi33d_vectors(Mreal, Qreal)
            END IF
          END IF

C         Rotate the complex block and retain its diagonal to first order.
          DO aidx = 1, n
            col = members(aidx)
            DO bidx = 1, n
              i = members(bidx)
              V(i,col) = DCMPLX(Qreal(i,col), 0.0d0)
            END DO
            DO bidx = 1, n
              i = members(bidx)
              DO pos = 1, n
                j = members(pos)
                lam(col) = lam(col)
     &            + Qreal(i,col)*A(i,j)*Qreal(j,col)
              END DO
            END DO
          END DO
        END IF
      END DO

C     First-order corrections between distinct diagonal groups.
      DO col = 1, 3
        DO i = 1, 3
          IF (group(i) .NE. group(col)) THEN
            numerator = DCMPLX(0.0d0, 0.0d0)
            DO j = 1, 3
              numerator = numerator + A(i,j)*V(j,col)
            END DO
            gap = lam(col) - D(i)
            V(i,col) = V(i,col) + numerator/gap
          END IF
        END DO
      END DO

C     Sort eigenpairs by eigenvalue real part.
      DO i = 1, 2
        DO j = i+1, 3
          IF (DBLE(lam(j)) .LT. DBLE(lam(i))) THEN
            ztmp = lam(i)
            lam(i) = lam(j)
            lam(j) = ztmp
            DO pos = 1, 3
              ztmp = V(pos,i)
              V(pos,i) = V(pos,j)
              V(pos,j) = ztmp
            END DO
          END IF
        END DO
      END DO

      RETURN
      END SUBROUTINE eig33z_near_diagonal

C----------------------------------------------------------------------
C     eig33z_rotated_fallback: Rotation-invariant eig fallback.
C
C     Diagonalize the real symmetric state with the fixed real Jacobi
C     helper, rotate the full complex perturbation into that principal
C     basis, apply eig33z_near_diagonal there, and rotate its vectors
C     back. This handles complex-step calls and repeated/near-repeated
C     pure values without assuming coordinate-axis alignment.
C----------------------------------------------------------------------
      SUBROUTINE eig33z_rotated_fallback(A, lam, V)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: lam(3), V(3,3)
      DOUBLE PRECISION :: Areal(3,3), Q(3,3)
      DOUBLE COMPLEX :: Aprin(3,3), Vprin(3,3)
      INTEGER :: i, j, k, l

      DO i = 1, 3
        DO j = 1, 3
          Areal(i,j) = DBLE(A(i,j))
        END DO
      END DO
      CALL jacobi33d_vectors(Areal, Q)

      Aprin = DCMPLX(0.0d0, 0.0d0)
      DO i = 1, 3
        DO j = 1, 3
          DO k = 1, 3
            DO l = 1, 3
              Aprin(i,j) = Aprin(i,j)
     &          + Q(k,i)*A(k,l)*Q(l,j)
            END DO
          END DO
        END DO
      END DO

      CALL eig33z_near_diagonal(Aprin, lam, Vprin)

      V = DCMPLX(0.0d0, 0.0d0)
      DO i = 1, 3
        DO j = 1, 3
          DO k = 1, 3
            V(i,j) = V(i,j) + Q(i,k)*Vprin(k,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE eig33z_rotated_fallback

C----------------------------------------------------------------------
C     eig33z: Eigenvalues and eigenvectors of 3x3 symmetric matrix
C
C     Distinct real spectra use the trigonometric solution. Repeated,
C     quasi-repeated, and complex-step paths use a real principal basis
C     and perturbation fallback.
C
C     Eigenvector column scaling/normalization is unspecified. Use
C     inv(V), not V^T, for reconstruction; normalize a column explicitly
C     only when a constitutive equation requires a unit direction.
C     Inside the quasi-repeated grouping band, only eigenspace-invariant
C     spectral reconstructions are part of the supported CS contract.
C
C     Near diagonal/repeated states call eig33z_near_diagonal, the
C     generated-Fortran mirror of tensor.py's perturbation fallback.
C----------------------------------------------------------------------
      SUBROUTINE eig33z(A, lam, V)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: lam(3), V(3,3)

C     --- Local variables ---
      DOUBLE COMPLEX :: p1, q, p2, p, r, phi
      DOUBLE COMPLEX :: B(3,3), C(3,3), M(3,3)
      DOUBLE COMPLEX :: zi, zacos, ztmp
      DOUBLE COMPLEX :: det33z
      DOUBLE COMPLEX :: r0(3), r1(3), r2(3)
      DOUBLE COMPLEX :: c1(3), c2(3), c3(3)
      DOUBLE COMPLEX :: nsq1, nsq2, nsq3, best_nsq
      DOUBLE PRECISION, PARAMETER ::
     &  PI = 3.14159265358979323846d0
      DOUBLE PRECISION :: twopi3, max_imag
      INTEGER :: i, j, k, best_idx

      zi = DCMPLX(0.0d0, 1.0d0)
      twopi3 = 2.0d0 * PI / 3.0d0

C     Complex-step path: rotate the real state to its principal basis
C     before applying the quasi-degenerate fallback. Repeated spectra
C     must not depend on alignment with the input coordinate axes.
      max_imag = 0.0d0
      DO i = 1, 3
        DO j = 1, 3
          max_imag = MAX(max_imag, ABS(AIMAG(A(i,j))))
        END DO
      END DO
      IF (max_imag .GT. 0.0d0) THEN
        CALL eig33z_rotated_fallback(A, lam, V)
        RETURN
      END IF

C     --- Invariants ---
      p1 = A(1,2)**2 + A(1,3)**2 + A(2,3)**2
      q  = (A(1,1) + A(2,2) + A(3,3)) / 3.0d0

C     B = A - q*I
      DO i = 1, 3
        DO j = 1, 3
          B(i,j) = A(i,j)
        END DO
      END DO
      B(1,1) = B(1,1) - q
      B(2,2) = B(2,2) - q
      B(3,3) = B(3,3) - q

      p2 = B(1,1)**2 + B(2,2)**2 + B(3,3)**2
     &   + 2.0d0 * p1
      p  = SQRT(p2 / 6.0d0)

C     Guard: A is a multiple of identity plus a tiny perturbation.
      IF (ABS(DBLE(p)) .LT. 1.0d-30) THEN
        CALL eig33z_rotated_fallback(A, lam, V)
        RETURN
      END IF

C     Nearly-diagonal guard (matches Python tensor.eig).
      IF (ABS(DBLE(p2)) .GT. 0.0d0 .AND.
     &    ABS(DBLE(p1)) .LT. 1.0d-14 * ABS(DBLE(p2))) THEN
        CALL eig33z_rotated_fallback(A, lam, V)
        RETURN
      END IF

C     C = B / p
      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = B(i,j) / p
        END DO
      END DO

C     r = det(C) / 2
      r = det33z(C) / 2.0d0

C     Repeated/near-repeated pure-real spectra also require the rotated
C     fallback. Raw cross-product columns are singular when a repeated
C     eigenspace is not aligned with the input axes.
      IF (ABS(1.0d0-ABS(DBLE(r))) .LE. 1.0d-10) THEN
        CALL eig33z_rotated_fallback(A, lam, V)
        RETURN
      END IF

C     Clamp real part before complex arccos, matching tensor.py eig().
C     Near repeated eigenvalues, roundoff can push DBLE(r) just outside
C     [-1, 1] and poison complex-step tangents with NaNs.
      r = DCMPLX(MAX(-1.0d0, MIN(1.0d0, DBLE(r))), AIMAG(r))

C     Complex arccos: zacos = -i * log(r + i*sqrt(1 - r^2))
      zacos = -zi * LOG(r + zi * SQRT(
     &  DCMPLX(1.0d0, 0.0d0) - r*r))
      phi = zacos / 3.0d0

C     Three eigenvalues
      lam(1) = q + 2.0d0*p*COS(phi)
      lam(2) = q + 2.0d0*p*COS(phi
     &       + DCMPLX(twopi3, 0.0d0))
      lam(3) = q + 2.0d0*p*COS(phi
     &       + DCMPLX(2.0d0*twopi3, 0.0d0))

C     Sort by real part (ascending, 3-element bubble sort)
      DO i = 1, 2
        DO j = i+1, 3
          IF (DBLE(lam(j)) .LT. DBLE(lam(i))) THEN
            ztmp = lam(i)
            lam(i) = lam(j)
            lam(j) = ztmp
          END IF
        END DO
      END DO

C     --- Eigenvectors via cross products of rows of (A - lam*I) ---
      DO k = 1, 3
C       M = A - lam(k) * I
        DO i = 1, 3
          DO j = 1, 3
            M(i,j) = A(i,j)
          END DO
        END DO
        M(1,1) = M(1,1) - lam(k)
        M(2,2) = M(2,2) - lam(k)
        M(3,3) = M(3,3) - lam(k)

C       Extract rows
        DO j = 1, 3
          r0(j) = M(1,j)
          r1(j) = M(2,j)
          r2(j) = M(3,j)
        END DO

C       Three candidate cross products
        CALL cross3z(r0, r1, c1)
        CALL cross3z(r0, r2, c2)
        CALL cross3z(r1, r2, c3)

C       Squared norms (complex)
        nsq1 = c1(1)*c1(1) + c1(2)*c1(2) + c1(3)*c1(3)
        nsq2 = c2(1)*c2(1) + c2(2)*c2(2) + c2(3)*c2(3)
        nsq3 = c3(1)*c3(1) + c3(2)*c3(2) + c3(3)*c3(3)

C       Pick best (largest |nsq|)
        best_idx = 1
        best_nsq = nsq1
        IF (ABS(nsq2) .GT. ABS(best_nsq)) THEN
          best_idx = 2
          best_nsq = nsq2
        END IF
        IF (ABS(nsq3) .GT. ABS(best_nsq)) THEN
          best_idx = 3
          best_nsq = nsq3
        END IF

C       Distinct-real path stores its raw cross-product column. The
C       eig33z API does not guarantee this scaling on every path.
        IF (ABS(best_nsq) .EQ. 0.0d0) THEN
C         Degenerate: coordinate basis fallback
          V(1,k) = DCMPLX(0.0d0, 0.0d0)
          V(2,k) = DCMPLX(0.0d0, 0.0d0)
          V(3,k) = DCMPLX(0.0d0, 0.0d0)
          V(k,k) = DCMPLX(1.0d0, 0.0d0)
        ELSE IF (best_idx .EQ. 1) THEN
          V(1,k) = c1(1)
          V(2,k) = c1(2)
          V(3,k) = c1(3)
        ELSE IF (best_idx .EQ. 2) THEN
          V(1,k) = c2(1)
          V(2,k) = c2(2)
          V(3,k) = c2(3)
        ELSE
          V(1,k) = c3(1)
          V(2,k) = c3(2)
          V(3,k) = c3(3)
        END IF
      END DO

      RETURN
      END SUBROUTINE eig33z

C----------------------------------------------------------------------
C     sqrtm33z: Matrix square root via eigendecomposition
C
C     sqrtm(A) = V * diag(sqrt(lam)) * inv(V)
C     Uses inv(V) (not V^T) for CS correctness.
C----------------------------------------------------------------------
      SUBROUTINE sqrtm33z(A, S)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: S(3,3)

      DOUBLE COMPLEX :: lam(3), V(3,3), Vinv(3,3)
      DOUBLE COMPLEX :: D(3,3), T(3,3)
      INTEGER :: i, j

      CALL eig33z(A, lam, V)
      CALL inv33z(V, Vinv)

C     D = diag(sqrt(lam))
      DO i = 1, 3
        DO j = 1, 3
          D(i,j) = DCMPLX(0.0d0, 0.0d0)
        END DO
      END DO
      D(1,1) = SQRT(lam(1))
      D(2,2) = SQRT(lam(2))
      D(3,3) = SQRT(lam(3))

C     S = V * D * Vinv
      CALL matmul33z(V, D, T)
      CALL matmul33z(T, Vinv, S)

      RETURN
      END SUBROUTINE sqrtm33z

C----------------------------------------------------------------------
C     logm33z: Matrix logarithm via eigendecomposition
C
C     logm(A) = V * diag(log(lam)) * inv(V)
C     For Hencky strain: E = 0.5 * logm(C)
C----------------------------------------------------------------------
      SUBROUTINE logm33z(A, L)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: L(3,3)

      DOUBLE COMPLEX :: lam(3), V(3,3), Vinv(3,3)
      DOUBLE COMPLEX :: D(3,3), T(3,3)
      INTEGER :: i, j

      CALL eig33z(A, lam, V)
      CALL inv33z(V, Vinv)

C     D = diag(log(lam))
      DO i = 1, 3
        DO j = 1, 3
          D(i,j) = DCMPLX(0.0d0, 0.0d0)
        END DO
      END DO
      D(1,1) = LOG(lam(1))
      D(2,2) = LOG(lam(2))
      D(3,3) = LOG(lam(3))

C     L = V * D * Vinv
      CALL matmul33z(V, D, T)
      CALL matmul33z(T, Vinv, L)

      RETURN
      END SUBROUTINE logm33z

C----------------------------------------------------------------------
C     expm33z: Matrix exponential via eigendecomposition
C
C     expm(A) = V * diag(exp(lam)) * inv(V)
C     For exponential map: Fp_new = expm(dt*Dp) * Fp_old
C----------------------------------------------------------------------
      SUBROUTINE expm33z(A, E)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: E(3,3)

      DOUBLE COMPLEX :: lam(3), V(3,3), Vinv(3,3)
      DOUBLE COMPLEX :: D(3,3), T(3,3)
      INTEGER :: i, j

      CALL eig33z(A, lam, V)
      CALL inv33z(V, Vinv)

C     D = diag(exp(lam))
      DO i = 1, 3
        DO j = 1, 3
          D(i,j) = DCMPLX(0.0d0, 0.0d0)
        END DO
      END DO
      D(1,1) = EXP(lam(1))
      D(2,2) = EXP(lam(2))
      D(3,3) = EXP(lam(3))

C     E = V * D * Vinv
      CALL matmul33z(V, D, T)
      CALL matmul33z(T, Vinv, E)

      RETURN
      END SUBROUTINE expm33z

C----------------------------------------------------------------------
C     polar33z: Right polar decomposition F = R * U
C
C     U = sqrtm(F^T * F),  R = F * inv(U)
C----------------------------------------------------------------------
      SUBROUTINE polar33z(F, R, U)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: F(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: R(3,3), U(3,3)

      DOUBLE COMPLEX :: FT(3,3), C(3,3), Uinv(3,3)

C     C = F^T * F
      CALL transpose33z(F, FT)
      CALL matmul33z(FT, F, C)

C     U = sqrtm(C)
      CALL sqrtm33z(C, U)

C     R = F * inv(U)
      CALL inv33z(U, Uinv)
      CALL matmul33z(F, Uinv, R)

      RETURN
      END SUBROUTINE polar33z

C----------------------------------------------------------------------
C     polar33z_iter: Right polar decomposition F = R * U
C
C     Iterative backend: uses sqrtm33z_iter for CS safety.
C----------------------------------------------------------------------
      SUBROUTINE polar33z_iter(F, R, U)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: F(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: R(3,3), U(3,3)

      DOUBLE COMPLEX :: FT(3,3), C(3,3), Uinv(3,3)

C     C = F^T * F
      CALL transpose33z(F, FT)
      CALL matmul33z(FT, F, C)

C     U = sqrtm(C),  Uinv = inv(sqrtm(C))
      CALL sqrtm33z_iter(C, U, Uinv)

C     R = F * inv(U)
      CALL matmul33z(F, Uinv, R)

      RETURN
      END SUBROUTINE polar33z_iter

C----------------------------------------------------------------------
C     sqrtm33z_iter: Matrix square root via Denman-Beavers iteration
C
C     Converges: Y -> sqrtm(A),  Z -> inv(sqrtm(A))
C     Fixed iteration count for CS safety (no branching).
C----------------------------------------------------------------------
      SUBROUTINE sqrtm33z_iter(A, S, Sinv)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: S(3,3), Sinv(3,3)

      DOUBLE COMPLEX :: Y(3,3), Z(3,3)
      DOUBLE COMPLEX :: Yinv(3,3), Zinv(3,3)
      DOUBLE COMPLEX :: half
      INTEGER, PARAMETER :: MAXITER = 20
      INTEGER :: iter, i, j

      half = DCMPLX(0.5d0, 0.0d0)

C     Y = A, Z = I
      DO i = 1, 3
        DO j = 1, 3
          Y(i,j) = A(i,j)
        END DO
      END DO
      CALL eye33z(Z)

      DO iter = 1, MAXITER
        CALL inv33z(Z, Zinv)
        CALL inv33z(Y, Yinv)
        DO i = 1, 3
          DO j = 1, 3
            Y(i,j) = half * (Y(i,j) + Zinv(i,j))
            Z(i,j) = half * (Z(i,j) + Yinv(i,j))
          END DO
        END DO
      END DO

      DO i = 1, 3
        DO j = 1, 3
          S(i,j)    = Y(i,j)
          Sinv(i,j) = Z(i,j)
        END DO
      END DO

      RETURN
      END SUBROUTINE sqrtm33z_iter

C----------------------------------------------------------------------
C     logm33z_iter: Matrix logarithm via inverse scaling & squaring
C
C     Step 1: B = A^{1/2^NSCALE}  (repeated square roots)
C     Step 2: Gregory series for log(B) where B ~ I
C     Step 3: log(A) = 2^NSCALE * log(B)
C     Fixed counts for CS safety.
C----------------------------------------------------------------------
      SUBROUTINE logm33z_iter(A, L)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: L(3,3)

      DOUBLE COMPLEX :: B(3,3), Bsqrt(3,3), Binvsqrt(3,3)
      DOUBLE COMPLEX :: BpI(3,3), BmI(3,3), BpI_inv(3,3)
      DOUBLE COMPLEX :: X(3,3), X2(3,3), Xpow(3,3)
      DOUBLE COMPLEX :: T1(3,3), II(3,3)
      DOUBLE COMPLEX :: scl
      INTEGER, PARAMETER :: NSCALE = 10
      INTEGER, PARAMETER :: NSERIES = 8
      INTEGER :: ks, i, j

C     Step 1: Repeated square roots -- B = A^{1/2^NSCALE}
      DO i = 1, 3
        DO j = 1, 3
          B(i,j) = A(i,j)
        END DO
      END DO
      DO ks = 1, NSCALE
        CALL sqrtm33z_iter(B, Bsqrt, Binvsqrt)
        DO i = 1, 3
          DO j = 1, 3
            B(i,j) = Bsqrt(i,j)
          END DO
        END DO
      END DO

C     Step 2: Gregory series for log(B) where B ~ I
C     X = (B - I) * inv(B + I)
      CALL eye33z(II)
      DO i = 1, 3
        DO j = 1, 3
          BpI(i,j) = B(i,j) + II(i,j)
          BmI(i,j) = B(i,j) - II(i,j)
        END DO
      END DO
      CALL inv33z(BpI, BpI_inv)
      CALL matmul33z(BmI, BpI_inv, X)

C     X2 = X * X
      CALL matmul33z(X, X, X2)

C     L = X,  Xpow = X  (start series)
      DO i = 1, 3
        DO j = 1, 3
          L(i,j)    = X(i,j)
          Xpow(i,j) = X(i,j)
        END DO
      END DO

C     L += Xpow * X2 / k  for k = 3, 5, 7, ..., 2*NSERIES+1
      DO ks = 3, 2*NSERIES+1, 2
        CALL matmul33z(Xpow, X2, T1)
        DO i = 1, 3
          DO j = 1, 3
            Xpow(i,j) = T1(i,j)
            L(i,j) = L(i,j)
     &        + Xpow(i,j) / DCMPLX(DBLE(ks), 0.0d0)
          END DO
        END DO
      END DO

C     Step 3: Undo scaling -- L = 2 * L * 2^NSCALE
      scl = DCMPLX(DBLE(2**(NSCALE+1)), 0.0d0)
      DO i = 1, 3
        DO j = 1, 3
          L(i,j) = L(i,j) * scl
        END DO
      END DO

      RETURN
      END SUBROUTINE logm33z_iter

C----------------------------------------------------------------------
C     expm33z_iter: Matrix exponential via scaling & squaring + Pade
C
C     Step 1: B = A / 2^NSCALE
C     Step 2: [2/2] Pade approximant for exp(B)
C     Step 3: E = exp(B)^{2^NSCALE}  (repeated squaring)
C     Fixed counts for CS safety.
C----------------------------------------------------------------------
      SUBROUTINE expm33z_iter(A, E)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: E(3,3)

      DOUBLE COMPLEX :: B(3,3), B2(3,3), II(3,3)
      DOUBLE COMPLEX :: N2(3,3), D2(3,3), D2inv(3,3)
      DOUBLE COMPLEX :: T1(3,3)
      DOUBLE COMPLEX :: scl, half, twelfth
      INTEGER, PARAMETER :: NSCALE = 10
      INTEGER :: ks, i, j

      half     = DCMPLX(0.5d0, 0.0d0)
      twelfth  = DCMPLX(1.0d0/12.0d0, 0.0d0)
      scl      = DCMPLX(DBLE(2**NSCALE), 0.0d0)

C     Step 1: B = A / 2^NSCALE
      DO i = 1, 3
        DO j = 1, 3
          B(i,j) = A(i,j) / scl
        END DO
      END DO

C     B2 = B * B
      CALL matmul33z(B, B, B2)

C     [2/2] Pade: exp(B) ~ inv(I - B/2 + B^2/12) * (I + B/2 + B^2/12)
      CALL eye33z(II)
      DO i = 1, 3
        DO j = 1, 3
          N2(i,j) = II(i,j) + half*B(i,j)
     &            + twelfth*B2(i,j)
          D2(i,j) = II(i,j) - half*B(i,j)
     &            + twelfth*B2(i,j)
        END DO
      END DO
      CALL inv33z(D2, D2inv)
      CALL matmul33z(D2inv, N2, E)

C     Step 3: Repeated squaring -- E = E^{2^NSCALE}
      DO ks = 1, NSCALE
        CALL matmul33z(E, E, T1)
        DO i = 1, 3
          DO j = 1, 3
            E(i,j) = T1(i,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE expm33z_iter

C======================================================================
C     CS-safe scalar trig/hyperbolic functions (DOUBLE COMPLEX)
C     Exact complex formulas -- safe for complex-step derivatives
C======================================================================

C----------------------------------------------------------------------
C     cs_sin: complex sine  (analytic continuation of DSIN)
C----------------------------------------------------------------------
      FUNCTION cs_sin(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DSIN(x)*DCOSH(y), DCOS(x)*DSINH(y))
      RETURN
      END FUNCTION cs_sin

C----------------------------------------------------------------------
C     cs_cos: complex cosine  (analytic continuation of DCOS)
C----------------------------------------------------------------------
      FUNCTION cs_cos(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DCOS(x)*DCOSH(y), -DSIN(x)*DSINH(y))
      RETURN
      END FUNCTION cs_cos

C----------------------------------------------------------------------
C     cs_tan: complex tangent  (analytic continuation of DTAN)
C----------------------------------------------------------------------
      FUNCTION cs_tan(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y, den
      x = DBLE(z)
      y = AIMAG(z)
      den = DCOS(2.0d0*x) + DCOSH(2.0d0*y)
      w = DCMPLX(DSIN(2.0d0*x)/den, DSINH(2.0d0*y)/den)
      RETURN
      END FUNCTION cs_tan

C----------------------------------------------------------------------
C     cs_sinh: complex hyperbolic sine
C----------------------------------------------------------------------
      FUNCTION cs_sinh(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DSINH(x)*DCOS(y), DCOSH(x)*DSIN(y))
      RETURN
      END FUNCTION cs_sinh

C----------------------------------------------------------------------
C     cs_cosh: complex hyperbolic cosine
C----------------------------------------------------------------------
      FUNCTION cs_cosh(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DCOSH(x)*DCOS(y), DSINH(x)*DSIN(y))
      RETURN
      END FUNCTION cs_cosh

C----------------------------------------------------------------------
C     cs_tanh: complex hyperbolic tangent
C----------------------------------------------------------------------
      FUNCTION cs_tanh(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y, den
      x = DBLE(z)
      y = AIMAG(z)
      den = DCOSH(2.0d0*x) + DCOS(2.0d0*y)
      w = DCMPLX(DSINH(2.0d0*x)/den, DSIN(2.0d0*y)/den)
      RETURN
      END FUNCTION cs_tanh

C----------------------------------------------------------------------
C     cs_erf: complex error function (CS-safe first-order approx)
C----------------------------------------------------------------------
      FUNCTION cs_erf(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      DOUBLE PRECISION, PARAMETER :: two_over_sqrt_pi =
     &  1.1283791670955126d0
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(ERF(x), two_over_sqrt_pi * EXP(-x*x) * y)
      RETURN
      END FUNCTION cs_erf

C----------------------------------------------------------------------
C     cs_erfc: complex complementary error function
C----------------------------------------------------------------------
      FUNCTION cs_erfc(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE COMPLEX :: cs_erf
      w = DCMPLX(1.0d0, 0.0d0) - cs_erf(z)
      RETURN
      END FUNCTION cs_erfc

C----------------------------------------------------------------------
C     cs_atan: complex arctangent (analytic continuation of DATAN)
C----------------------------------------------------------------------
      FUNCTION cs_atan(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w, zi
      zi = DCMPLX(0.0D0, 1.0D0)
      w = (LOG(1.0D0 + zi*z) - LOG(1.0D0 - zi*z)) / (2.0D0*zi)
      RETURN
      END FUNCTION cs_atan

C----------------------------------------------------------------------
C     cs_acos: complex arccos  (analytic continuation of DACOS)
C----------------------------------------------------------------------
      FUNCTION cs_acos(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      w = -DCMPLX(0.0D0, 1.0D0) * LOG(z + DCMPLX(0.0D0, 1.0D0)
     &    * SQRT(1.0D0 - z**2))
      RETURN
      END FUNCTION cs_acos

C----------------------------------------------------------------------
C     cs_cubic_roots: all roots of a*x**3 + b*x**2 + c*x + d = 0
C     Depressed-cubic + Cardano, all in DOUBLE COMPLEX (CS-safe).
C----------------------------------------------------------------------
      SUBROUTINE cs_cubic_roots(a, b, c, d, r1, r2, r3)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a, b, c, d
      DOUBLE COMPLEX, INTENT(OUT) :: r1, r2, r3
      DOUBLE COMPLEX :: p, q, Delta, sqrt_Delta, u, v, shift
      DOUBLE COMPLEX :: t1, t2, t3
      DOUBLE COMPLEX :: half, third, one, two, three, nine
      DOUBLE COMPLEX :: twentyseven

      half  = DCMPLX(0.5d0, 0.0d0)
      third = DCMPLX(1.0d0/3.0d0, 0.0d0)
      one   = DCMPLX(1.0d0, 0.0d0)
      two   = DCMPLX(2.0d0, 0.0d0)
      three = DCMPLX(3.0d0, 0.0d0)
      nine  = DCMPLX(9.0d0, 0.0d0)
      twentyseven = DCMPLX(27.0d0, 0.0d0)

C     Depress the cubic: x = t - b/(3a)
C     t**3 + p*t + q = 0
      p = (three*a*c - b*b) / (three*a*a)
      q = (two*b**3 - nine*a*b*c + twentyseven*a*a*d)
     &    / (twentyseven*a**3)

C     Discriminant
      Delta = (q/two)**2 + (p/three)**3

C     Cardano terms
      sqrt_Delta = SQRT(Delta)
      u = (-q/two + sqrt_Delta)**third
C     v chosen so that u*v = -p/3 (avoids branch-cut ambiguity).
C     Guard u=0 (triple-root / p=0 case) by computing v independently.
      IF (ABS(u) .GT. 1.0d-30) THEN
        v = -p / (three*u)
      ELSE
        v = (-q/two - sqrt_Delta)**third
      END IF

C     Three roots in t
      t1 = u + v
      t2 = -half*(u+v) + DCMPLX(0.0d0, DSQRT(3.0d0)/2.0d0)*(u-v)
      t3 = -half*(u+v) - DCMPLX(0.0d0, DSQRT(3.0d0)/2.0d0)*(u-v)

C     Shift back
      shift = b / (three*a)
      r1 = t1 - shift
      r2 = t2 - shift
      r3 = t3 - shift

      RETURN
      END SUBROUTINE cs_cubic_roots
