"""Generate the pressure-based gel Hex8 local-pressure UEL.

This is the CURRENT declaration-to-Fortran pipeline for the
three-dimensional morphing example: the minimal pressure-coupled gel
declaration of the paper (Fig. 2 / Listing S1) on a Hex8 element with
one condensed local pressure. Running it emits
``pressuregel_local_pressure_hex8.for`` next to this script.

The EXACT source submitted with the completed morphing run is preserved
unmodified under ``archived_submitted/``; it was generated by an earlier
state of the same pipeline and carries a historical internal symbol
prefix. The current pipeline regenerates a functionally equivalent
element with today's generator (including its procedure-dispatch and
det(F) guards).
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import abaqus_ufl as au
from abaqus_ufl.core.tensor import det, exp, inv, log


class PressureGelMaterial(au.Material):
    """Pressure-coupled gel: neo-Hookean network + Flory--Huggins mixing."""

    props = dict(G=1.0, K=100.0, chi=0.1, D=5.0e-9, mu0=0.0,
                 Omega=1.0e-4, Rgas=8.314, theta=298.0, phi0=0.5)

    def stress_PK1(self, F, p, mu):
        return self.G * (F - inv(F).T) + p * inv(F).T

    def pressure_resid(self, F, p, mu):
        J = det(F)
        Je = exp(p / self.K)
        phi = self.phi0 * Je / J
        return (mu - self.mu0
                - self.Rgas * self.theta
                * (log(1.0 - phi) + phi + self.chi * phi ** 2)
                + (phi / self.phi0) * self.Omega * p)

    def solvent_flux(self, F, p, mu, grad_mu):
        J = det(F)
        Je = exp(p / self.K)
        phi = self.phi0 * Je / J
        Cinv = inv(F.T @ F)
        cR0 = (1.0 - self.phi0) / self.Omega
        cR = cR0 + (self.phi0 - phi) / (self.Omega * phi)
        M = self.D * cR / (self.Rgas * self.theta)
        return -M * (Cinv @ grad_mu)

    def solvent_storage(self, F, F_old, p, p_old, dt):
        J = det(F)
        J_old = det(F_old)
        Je = exp(p / self.K)
        Je_old = exp(p_old / self.K)
        return (J / Je - J_old / Je_old) / (self.Omega * dt)


class PressureGelLocalPressureHex8(au.WeakForm):
    material = PressureGelMaterial
    ndim = 3

    def define_fields(self):
        self.u = au.VectorField('u', degree=1)
        self.mu = au.ScalarField('mu', degree=1)
        self.p = au.LocalScalar('p', storage='SVARS',
                                condensed=True, initial=0.0)

    def momentum_equation(self, v, F, p, mu):
        return self.material.stress_PK1(F, p, mu)

    def pressure_equation(self, q, F, p, mu):
        return self.material.pressure_resid(F, p, mu)

    def transport_equation(self, w, F, p, mu, grad_mu, F_old, p_old, dt):
        c_dot = self.material.solvent_storage(F, F_old, p, p_old, dt)
        j_R = self.material.solvent_flux(F, p, mu, grad_mu)
        return c_dot, j_R


if __name__ == '__main__':
    problem = PressureGelLocalPressureHex8()
    if not problem.verify():
        raise SystemExit('local response verification failed')
    out = os.path.join(HERE, 'pressuregel_local_pressure_hex8.for')
    au.generate_uel(problem, out, element='Hex8',
                    formulation='local_pressure',
                    mat_prefix='pressuregel')
    print('Generated', out)
